version: 0.2

phases:
#  install:
#    commands:
      #- nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      #- timeout 15 sh -c "until docker info; do echo .; sleep 5; done"

  #pre_build:
  #  commands:
  #    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 403291311909.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - git clone https://github.com/mstanchev-hs/cb-custom-image.git
      - ls -latr cb-custom-image/
      - chmod 755 cb-custom-image/Chef_Cookbook_Promote.sh
      - cb-custom-image/Chef_Cookbook_Promote.sh $chef_environment $cookbook $version $WORKSPACE
      #- echo "Hello World from buildspec!"
